[env:m5stack-cardputer]
platform = espressif32 @ ^6.7.0
board = m5stack-cardputer
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unit-NFC
build_flags =
    -DUSING_UNIT_NFC_U216
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -Os
